Update plugins, add maven site
terrestris/geoserver-notification-http pull request #3
Opened 2022-02-18 12:50 UTC by hwbllmnn

@terrestris/devs Please review.

2022-02-18 16:20 UTC, marcjansen requested changes

2022-02-18 16:20 UTC, marcjansen commented on src/site/site.xml
> +  ~
This is not correct

2022-02-18 16:20 UTC, marcjansen commented on src/site/site.xml
> +<project name="GPRO Webgis">
Same here

2022-02-21 06:54 UTC, hwbllmnn commented on src/site/site.xml
> +  ~
Right, fixed in 159eeb7

2022-02-21 06:54 UTC, hwbllmnn commented on src/site/site.xml
> +<project name="GPRO Webgis">
Right, fixed in 159eeb7

2022-02-21 11:00 UTC, KaiVolland approved these changes

2022-02-21 14:35 UTC, merged